books/urls.py
from django.urls import path
from . import  views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_books', views.get_books_by_title_or_author, name='get_books_title_author')
]

django_book_api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
]

handler404 = 'books.views.view_404'

books/models.py
from django.db import models

# Create your models here.

books/views.py
from django.shortcuts import render, redirect
import requests, json


#Variables statics
ERROR_MESSAGE_FORM = "If you want to search for books you need the title or name of the author."
LINK_SEARCH_API_LIBRARY = "https://openlibrary.org/search.json?"

def index(request):
    return render(request, 'books/index.html', {})


def get_books_by_title_or_author(request):
    """
    This method receives the title and name of the author to search through the GET 
    protocol. Verify that at least one of the two is 
    present, otherwise it returns an error to the initial page.
    Makes the request to the Open Library API and returns the most important values.

    Args:
        request (_type_): request from page

    Returns:
        books from API Open Library
    """
    there_is_at_least_one = request.GET['search_title'] or request.GET['search_author']
    
    if not there_is_at_least_one:
        return render(request, 'books/index.html', {'error_form': ERROR_MESSAGE_FORM})
    
    title_clear = str(request.GET['search_title']).strip().replace(" ","+")
    author_clear = str(request.GET['search_author']).strip().replace(" ","+")
    
    params = {'fields':'title, author_name, edition_count, edition_key, publisher, language, publish_date, seed, first_publish_year'}
    
    if title_clear and author_clear:
        request_api = requests.get(LINK_SEARCH_API_LIBRARY, params={'title': title_clear, 'author':author_clear} | params)
        
    elif title_clear:
        request_api = requests.get(LINK_SEARCH_API_LIBRARY, params={'title': title_clear} | params)
    
    else:
        request_api = requests.get(LINK_SEARCH_API_LIBRARY, params={'author':author_clear} | params)
        
    json_data = json.loads(request_api.text)
    
    return render(request, 'books/index.html', {'books':json_data['docs']})


def view_404(request, exception=None):
    """
    Redirects to the main page if it fails due to a 404 error

    Args:
        request (_type_): use in the future
        exception (_type_, optional): Other acttions. Defaults to None.

    Returns:
        redirect books/
    """
    return redirect('/books/')

books/templates/books/card_book.html
{% load static %}


<div class="card w-60 mb-2">
    <div class="card-body">
      <h4 class="card-title">{{book.title}}</h4>
      <p class="card-text"> <strong> Author:</strong> {% for author in book.author_name %} {{author}}. {% endfor %}</p>
      <p class="card-text"> <strong> Publisher:</strong> {% for publisher in  book.publisher %} {{publisher}} - {% endfor %}</p>
      <p class="card-text"> <strong> Language: </strong> {% for language  in  book.language %} {{ language | capfirst }} -  {% endfor %}</p>
      <p class="card-text"> <strong> Counts Editions: </strong> {{book.edition_count}}</p>
      <p class="card-text"> <strong> First Publish Year: </strong>  {{book.first_publish_year}}</p>
      <p class="card-text"> <strong> Publish Date: </strong>  {% for publish_date in book.publish_date %} {{publish_date}} -  {% endfor %}</p>

      <a href="https://openlibrary.org/{{book.seed.0}}" target="_blank" class="btn btn-primary">See more at Open Library.</a>
    </div>
</div>

books/templates/books/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search books</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>
<body>

    <div class="container-fluid">
        <div class="container-fluid">
            <nav class="navbar bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="60" height="48" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                          </svg>
                        Search Books from Open Library JSON API
                    </a>
                </div>
            </nav>
        </div>

        <hr>
    
        <div class="container">
            <div class="row g-2">
              <div class="col-4">
                <div class="container text-center">
                    <h3>Search book by Author o Title <span class="badge bg-secondary"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                      </svg> </span></h3>
    
                      <hr>
    
                      <form action="{% url 'books:get_books_title_author' %}" method="get">
    
                        {% if error_form %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    {{error_form}}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                        {% endif %}
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="floatingInputTitle" name="search_title">
                            <label for="floatingInputTitle">Search by Title</label>
                        </div>
                        <h3>Or</h3>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="floatingInputAuthor" name="search_author">
                            <label for="floatingInputAuthor">Search by Author</label>
                        </div>
    
                        <button type="submit" class="btn btn-primary">Search</button>
    
                      </form>
    
                </div>
              </div>
    
              <div class="col-8">

                {% if books %}
                
                    {% for book in books %}

                        {% include 'books/card_book.html' %}

                    {% endfor %}

                {% else %}

                <div class="container text-center">

                    <h3>No hay libros por ver ...</h3>
                    <img src="https://images.unsplash.com/photo-1519682337058-a94d519337bc?ixlib=rb-4.0.3" width="60%" height="60%" alt="" srcset="">
                </div>

                {% endif %}
    
              </div>
            </div>
        </div>
    </div>
 
    
</body>
</html>